site_name: mkdocs
site_url: https://jajera.github.io/mkdocs/
site_author: John Ajera
nav:
  - Home: index.md

repo_name: jajera/mkdocs
repo_url: https://github.com/jajera/mkdocs

theme:
  name: material
  palette:
      primary: 'red'
      accent: 'red'

markdown_extensions:
  - toc:
      baselevel: 2
      permalink: true
  - admonition
  - footnotes
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
markdown_extensions:
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true

# extra_css:
#   - css/neoteroi-mkdocs.css

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - include_dir_to_nav
  - pdf-export:
      combined: true
      enabled_if_env: ENABLE_PDF_EXPORT
  - awesome-pages:
      collapse_single_pages: true
      strict: false