site_name: mkdocs
site_url: https://jajera.github.io/mkdocs/
site_author: John Ajera

repo_name: jajera/mkdocs
repo_url: https://github.com/jajera/mkdocs

markdown_extensions:
  - toc:
      baselevel: 2
      permalink: true
  - admonition
  - footnotes
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
markdown_extensions:
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true

plugins:
  - include_dir_to_nav:
      recurse: true
      sort_file: true
      sort_directory: true
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - awesome-pages:
      collapse_single_pages: true
      strict: false

theme:
  name: material
  palette:
      primary: 'indigo'
      accent: 'indigo'

extra_javascript:
    - 'javascripts/extra.js'
extra_css:
    - 'stylesheets/extra.css'

nav:
  - Home: index.md
