site_name: mkdocs
site_url: https://jajera.github.io/mkdocs/
nav:
  - Home: index.md
  - About: about.md
theme: readthedocs

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - css/neoteroi-mkdocs.css

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - minify:
      minify_html: true
  - include_dir_to_nav