name: markdown-lint
on:
  push:
    branches:
      - main
permissions:
  statuses: write
  checks: write
  contents: read
  pull-requests: read
jobs:
  markdown-lint:
    uses: platformfuzz/actions/.github/workflows/markdown-lint.yml@main